on:
  release:
    types:
      - created

name: Build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Get Release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      - name: Write manifest
        run: sed -i 's/%MODPACK_VERSION%/${{ steps.get_release.outputs.tag_name }}/g' manifest.json
      - name: Zip Modpack
        run: zip -r modpack.zip *
      - name: Copy files for CurseForge upload
        run: |
          mkdir -p curse_upload
          cp ./modpack.zip './curse_upload/Aur-${{ steps.get_release.outputs.tag_name }}.zip'
      - name: Upload to CurseForge
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.API_TOKEN }}
          project-id: '766928'
          modpack-path: './curse_upload/Aur-${{ steps.get_release.outputs.tag_name }}.zip'
          game-version: '1.12.2'
          display-name: 'Aur. ${{ steps.get_release.outputs.tag_name }}'
          release-type: "beta"
      - name: prof
        uses: softprops/action-gh-release@v1
